# Generated by Django 5.2.7 on 2025-11-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
