# Generated by Django 5.2.7 on 2025-12-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0002_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
